server:
  port: 80
#  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    servlet:
      path: /
  mail:
    host: smtp.qq.com
    username: immortal_identity@qq.com
    password: cdunyedvsbulfedj
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    port: 465

mail:
  fromMail:
    addr: immortal_identity@qq.com
